baseURL: "https://timschutz.org" 
title: Tim Schütz
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    twitter: tmschtz

taxonomies:
    tag: tags

menu:
    main:
        - name: About
          url: /about/
          weight: 1
        - name: Projects
          url: /projects/
          weight: 2
        - name: Writing
          url: /publications/
          weight: 3
        - name: Talks
          url: /talks/
          weight: 4
        - name: Visual
          url: /visual/
          weight: 5
        - name: Teaching
          url: /teaching/
          weight: 6
        - name: CV
          url: https://drive.google.com/file/d/1okKzZGBb5P5YXcsJ6Qtmm7D97V13EyLk/view
          weight: 7

params:
    description: "I'm a social scientist studying the role of data in environmental governance, research, and communication. Currently affiliated with EcoGovLab at the University of California, Irvine."
    author: Tim Schütz
    googleAnalyticsID: ""
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Tim Schütz
          subtitle: "I'm a trained social scientist and digital designer working on environmental governance, politics, and pedagogy. I also help build public knowledge infrastructures, community archives, and open-access teaching materials. Currently affiliated researcher with the EcoGovLab at the University of California, Irvine."
          imageUrl: "https://pbs.twimg.com/profile_images/1850306863138770944/rZLxavvt_400x400.jpg"
          imageWidth: 170
          imageHeight: 170
          imageTitle: Tim Schütz
          buttons:
            - name: About
              url: /about/
            - name: Publications
              url: /publications/
            - name: Projects
              url: /projects/
            - name: Talks
              url: /talks/
            - name: Visual
              url: /visual/
            - name: Teaching
              url: /teaching/
            - name: CV
              url: https://drive.google.com/file/d/1okKzZGBb5P5YXcsJ6Qtmm7D97V13EyLk/view
              
    socialIcons:
        - name: Email
          url: "mailto:tschuetz@uci.edu"
        - name: Google Scholar
          url: "https://scholar.google.com/citations?user=KQlghMUAAAAJ&hl=en"
        - name: LinkedIn
          url: "https://www.linkedin.com/in/tim-sch%C3%BCtz-0b6924127/"
        - name: Twitter
          url: "https://twitter.com/tmschtz"
        - name: YouTube
          url: "https://www.youtube.com/channel/UC9WaeK29i2L50pQ3osSrR8w?app=desktop"
        - name: GitHub
          url: "https://github.com/timschuetz"

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Tim Schütz"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
